### ISSUE TITLE
Error 499 or 504 when worker is processing a long job

### ISSUE THREAD

**Issue by waissbluth** [tawan/active-elastic-job#93] opened 2018-08-14 20:05 UTC
I'm not sure if this is actually a bug or misconfiguration, but for long-running jobs (i.e. jobs that take longer than the "Connection timeout" of 60 seconds (which is the maximum), nginx returns error 499 (`[14/Aug/2018:18:25:05 +0000] "POST / HTTP/1.1" 499 0 "-" "aws-sqsd/2.3" "-"`) or 504 (`[14/Aug/2018:20:03:40 +0000] "POST / HTTP/1.1" 504 183 "-" "aws-sqsd/2.3" "-"`) even as the worker actually picked up the job and is processing it.

I gather that the server is "unresponsive" and does not acknowledge that it is processing the job and therefore it is returned to the queue before the Visibility Timeout is over.

This is Rails 4.2.10 and active-elastic-job 2.0.1.

**Comment by waissbluth** [comment] 2018-08-14 20:10
Seems related to #56; however, we are not running rack-timeout.

**Comment by joeyparis** [comment] 2021-01-04 15:56
@waissbluth I believe this to be a duplicate of #56. See the solution here: https://github.com/tawan/active-elastic-job/issues/56#issuecomment-750894893. I've also included this in the documentation for the upcoming V3 release.

**Closed by joeyparis** 2021-01-04 15:56 UTC
