### ISSUE TITLE
Has this project been abandoned?

### ISSUE THREAD

**Issue by eamon-hguk** [tawan/active-elastic-job#76] opened 2017-10-20 09:50 UTC
I notice there is no activity on this project in terms of merges, release etc, can you let us know if has been abandoned so users can consider other options.

Thank you

**Comment by hurrycaner** [comment] 2017-10-31 10:59
@tawan ?

**Comment by tawan** [comment] 2017-11-06 01:07
Hi @eamon-hguk @hurrycaner 

This project has not been abandoned. I will look into open issues next weekend, when I have more time on my hands.

Thanks,

Tawan

**Comment by eamon-hguk** [comment] 2017-11-06 12:42
Great to hear, thank you for your effort!

Eamon

**Comment by oamado** [comment] 2018-04-16 19:15
so, can you close this issue? @tawan Thanks for your efort and your time

**Comment by jpsilvashy** [comment] 2018-05-25 02:00
@tawan, any way we can help out? We depend on this project. Got a todo list?

**Comment by tawan** [comment] 2018-05-25 02:09
@jpsilvashy  Thanks for reaching out. I guess I have to admit that I need help with the backlog. Are you interested to taking on some of the todos?

**Comment by marcgreenstock** [comment] 2018-08-10 09:17
@tawan I'd like to help out too if you could do with the help in testing and merging some of the pull requests.

**Comment by tawan** [comment] 2018-08-20 00:55
@jpsilvashy If you have time, I'd like to invite you to prioritize the open issues and create a list of the top 5. I don't use this project in production, therefore I'm don't have visibility in to what issues are the most pressing.

@marcgreenstock Let me explain the biggest blocker for contributing to the project. The integration tests need to run against resources in AWS. Currently, I run the tests against resources in my personal AWS account. Some resources (the EB application) need to be manually set up before running the tests. After the test, the resources need to be destroyed in order to prevent costs.

In order to achieve a fully automated integration test suite, I plan to do the following:

* Deprecate the usage of the aws-cli and replace them with API calls of the pure Ruby implementation. For example all system calls in [spec/helpers.rb](https://github.com/tawan/active-elastic-job/blob/master/spec/helpers.rb) 
* Create all AWS resources before running the tests
* Remove all AWS resources after the tests have run.

I tried to automatically lunch the EB environments in this [commit](https://github.com/tawan/active-elastic-job/commit/f9ea8aa9c33d6bb173cb05b9a8b877a958118601), but I'm not happy with its implementation.

Would you be interested in helping designing and implementing such an approach?

@jpsilvashy @marcgreenstock I would also be interested to onboard additional maintainers (with commit privileges). Are you interested in taking on more responsibility for this project?

**Comment by marcgreenstock** [comment] 2018-08-20 12:03
Hi @tawan Thanks for this. I can see how the integration tests create a huge bottle neck so I would like to suggest replacing EB integration with local a integration suite using a dummy app instead.

[SQS messages](https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/using-features-managing-env-tiers.html#worker-daemon) and [Periodic tasks](https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/using-features-managing-env-tiers.html#worker-periodictasks) are delivered via HTTP, there is no special protocol or behaviour involved, so I feel maintaining a full integration test suite on a real EB environment does not provide any more confidence than what a local integration suite can offer. If anything, a real EB integration suite results in less confidence because of the lack of transparency.

Replacing EB integration suite with a local integration suite will be easier to maintain and enable contributors to test their PR's with confidence resulting in a faster PR to release turn-around.

I can't foresee any bugs or regressions being introduced that could not have been caught by a local suite, but if they do, they will be quickly caught by the community of users that use this gem in production (myself included).

As for taking on additional responsibilities, I would be more than happy to help, we rely on this project immensely, so for me, dedicating some time to this project makes complete sense.

**Comment by tawan** [comment] 2018-09-05 01:43
@marcgreenstock  Thanks for your input. I'm working on a new release process that intends to address the issues. I will connect with you by mail if that's ok.

**Comment by marcgreenstock** [comment] 2018-09-06 12:29
@tawan, sure please email me.

**Comment by rubyisbeautiful** [comment] 2018-11-09 14:09
@tawan and @marcgreenstock we also use this in production, and as far as I can tell, no other gem that does what this one does.  The alternatives available are to hijack EB with an off the shelf asynchronous processor (resque et al).   
There is in particular, a lot of folks waiting to see the outcome of #88.  There is a PR already, which I have been using in production (albeit on a pretty small application).  Anything I can do to help, too, let me know.

**Comment by swaincreates** [comment] 2019-02-14 15:05
Is it safe to say this project is abandoned? Issue #88 is pretty critical

**Comment by joeyparis** [comment] 2019-11-13 21:45
@swaincreates it does look like this repo has been abandoned. It would be great to see it passed on to someone else who is able to continue supporting its development.

**Comment by tawan** [comment] 2020-01-21 00:18
Hi all who are following this issue,

I hardly find the time to maintain this project as a single contributor (which is kind of obvious from the pending PRs and open issues). I'm looking for interested collaborators. If you want to help out to maintain this project, then please +1 this comment and I will add you as a collaborator.

Many thanks in advance,

Tawan

**Comment by tawan** [comment] 2020-01-30 01:10
Thanks @swaincreates and @joeyparis for stepping up. I sent you an invite for collaboration. Other are still welcome too!

**Comment by swaincreates** [comment] 2020-01-30 02:38
Thanks @tawan will try to get up to speed soon and start helping out!

**Comment by joeyparis** [comment] 2020-12-23 18:21
I have recently taken over this project (along with the help of some other collaborators). I could definitely use some help, especially when it comes to spec testing/integration testing as they're not my strong area. I'm going to go ahead and close this issue now. Feel free to open a new one if you have anything you want to be fixed in version 3.

**Closed by joeyparis** 2020-12-23 18:21 UTC
